volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dbp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d dbp" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: host=postgres port=5432 user=admin password=password dbname=dbp sslmode=disable
      DATABASE_TEST_URL: host=postgres port=5432 user=admin password=password dbname=dbp_test sslmode=disable
      USERNAME: tecnico@prefeitura.rio
      PASSWORD: painel@2024
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    ports:
      - "3000:3000"