volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dbp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init_test.sql:/docker-entrypoint-initdb.d/init_test.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d dbp" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: host=postgres port=5432 user=admin password=password dbname=dbp sslmode=disable
      DATABASE_TEST_URL: host=postgres port=5432 user=admin password=password dbname=dbp_test sslmode=disable
      JWT_SECRET: jwt_super_secret
      DEV: true
    ports:
      - "8080:8080"